# Generated by Django 4.1.4 on 2022-12-07 12:09

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtubers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='youtuber',
            name='camera_type',
            field=models.CharField(choices=[('Canon', 'Canon'), ('Sony', 'Sony'), ('Nikon', 'Nikon'), ('Panasonic', 'Panasonic'), ('Olympus', 'Olympus'), ('Pentax', 'Pentax'), ('other', 'other')], max_length=255),
        ),
        migrations.AlterField(
            model_name='youtuber',
            name='category',
            field=models.CharField(choices=[('Vlogs', 'Vlogs'), ('Film-making', 'Film-making'), ('Cooking', 'Cooking'), ('Comedy', 'Comedy'), ('Educational', 'Educational'), ('Spiritual', 'Spiritual'), ('Other', 'Other')], max_length=255),
        ),
        migrations.AlterField(
            model_name='youtuber',
            name='crew',
            field=models.CharField(choices=[('Solo', 'Solo'), ('Small', 'Small'), ('Large', 'Large')], max_length=255),
        ),
        migrations.AlterField(
            model_name='youtuber',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
