# Generated by Django 4.1.4 on 2022-12-07 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Team',
        ),
    ]
